# Copyright © 2018 Hugo Locurcio and contributors - CC0 1.0 Universal
# See `LICENSE.md` included in the source distribution for details.

jobs:
  # Installs and uninstalls every package in the bucket
  # This is done to ensure URLs used in manifests are still functional
  - job: test
    condition: eq(variables['Build.Reason'], 'Schedule')
    pool:
      vmImage: vs2017-win2016
      steps:
        - powershell: |
            # Install Scoop
            Set-ExecutionPolicy RemoteSigned -scope CurrentUser
            iex (new-object net.webclient).downloadstring('https://get.scoop.sh')

            # Install packages
            Get-ChildItem *.json | Foreach-Object {
                scoop install "$($_.BaseName).json"
                scoop uninstall "$($_.BaseName)"
            }
